repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100, --target-version=py39]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: ^.bumpversion.cfg
      - id: trailing-whitespace
        exclude: ^.bumpversion.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910-1"
    hooks:
      - id: mypy
        name: Lint nest with mypy
        files: ^py_nest_thermostat/
        entry: mypy py_nest_thermostat/
        pass_filenames: false
        args: ["--ignore-missing-imports", "--python-version=3.9"]
        additional_dependencies:
          - "types-all"
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        name: Sort import with isort
        args: ["-m3", "-w 100", "--tc"]
        # exclude: ^tests/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        exclude: ^tests/
        args: ["--max-line-length=120", "--ignore=W503"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
